# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='active',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='updated',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
