# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170421_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Price_B',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Price_C',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Price_D',
        ),
    ]
