# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Age', models.IntegerField(max_length=5)),
                ('Address', models.TextField(max_length=500)),
                ('Contact', models.IntegerField(max_length=15)),
                ('Gender', models.TextField(max_length=10)),
                ('State', models.TextField(max_length=20)),
                ('Country', models.TextField(max_length=20)),
                ('Email', models.IntegerField(max_length=5)),
                ('Password', models.TextField(max_length=500)),
                ('Joined_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
