# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Email',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Password',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='State',
            field=models.TextField(max_length=25),
        ),
    ]
