# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userform', '0002_auto_20170421_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='State',
            field=models.CharField(max_length=25),
        ),
    ]
