# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='A',
            new_name='Price_A',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='B',
            new_name='Price_B',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='C',
            new_name='Price_C',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='D',
            new_name='Price_D',
        ),
    ]
